### ISSUE TITLE
RequireJS issue

### ISSUE THREAD

**Issue by thiagofesta** [maenu/grunt-template-jasmine-istanbul#10]
I had my Jasmine tests running fine with requireJS. I use connect to create the webserver and run the tests.

When I tried to add the istanbul i get that:
```
>> ReferenceError: Can't find variable: __coverage__ at
>> http:\127.0.0.1:7788\node_modules\grunt-template-jasmine-istanbul\src\main\js\reporter.js:4
>> http:\127.0.0.1:7788\.grunt\grunt-contrib-jasmine\jasmine.js:1788
>> http:\127.0.0.1:7788\.grunt\grunt-contrib-jasmine\jasmine.js:2160
>> http:\127.0.0.1:7788\.grunt\grunt-contrib-jasmine\jasmine.js:2144
>> http:\127.0.0.1:7788\.grunt\grunt-contrib-jasmine\jasmine.js:2106
>> http:\127.0.0.1:7788\.grunt\grunt-contrib-jasmine\jasmine.js:2092
>> http:\127.0.0.1:7788\.grunt\grunt-contrib-jasmine\jasmine.js:2478
>> http:\127.0.0.1:7788\.grunt\grunt-contrib-jasmine\jasmine.js:2522
>> http:\127.0.0.1:7788\.grunt\grunt-contrib-jasmine\jasmine.js:2106
>> http:\127.0.0.1:7788\.grunt\grunt-contrib-jasmine\jasmine.js:2092
>> http:\127.0.0.1:7788\.grunt\grunt-contrib-jasmine\jasmine.js:2350
>> http:\127.0.0.1:7788\.grunt\grunt-contrib-jasmine\jasmine.js:2377
>> http:\127.0.0.1:7788\.grunt\grunt-contrib-jasmine\jasmine.js:2106
>> http:\127.0.0.1:7788\.grunt\grunt-contrib-jasmine\jasmine.js:2086
```

**Comment by ryan0122** [comment]
I'm having similar issues. Here is my GruntFile:


    module.exports = function (grunt){
    return {
        coverage: {
            src: ['./src/scripts/sc/*.js'],
            options: {
                vendor: [
                    './src/libs/jquery-1.11.0.js',
                    './src/libs/jasmine-jquery/lib/jasmine-jquery.js'],
                specs: './test/spec/**/*.js',
                summary: true,
                template: require('grunt-template-jasmine-istanbul'),
                templateOptions: {
                    coverage: 'bin/coverage/coverage.json',
                    report: 'bin/coverage',
                    thresholds: {
                        lines: 50,
                        statements: 75,
                        branches: 75,
                        functions: 90
                    },
                    template: require('grunt-template-jasmine-requirejs'),
                    templateOptions: {
                        requireConfigFile: './src/scripts/config.js',
                        requireConfig: {
                            waitSeconds: 10,
                            baseUrl: './src/scripts',
                            callback: function () {
                                window.doNotStartApp = true;
                                console.log('window.doNotStartApp=' + window.doNotStartApp);
                                window.applicationClassName = 'app';
                            }
                        }
                    }
                }
            }
        }
     }
  

With this configuration I get the error:

    >> ReferenceError: Can't find variable: __coverage__

I tried changing the baseUrl as suggested above but that results in:

     >> Error: scripterror: Illegal path or script error: 

However when I try the [requirejs-client-example](https://github.com/maenu/grunt-template-jasmine-istanbul-example/tree/requirejs-client) I get the following error:

     >> Error: scripterror: Illegal path or script error: 

I've really been wasting a lot of time on this. Any other suggestions?

**Comment by gyandeeps** [comment]
Please reopen if the issue persists.
