### ISSUE TITLE
Jasmine waitsFor issue

### ISSUE THREAD

**Issue by vinayvik** [maenu/grunt-template-jasmine-istanbul#27]
With istanbul trying to use runs -> waitsFor -> runs, but it seems it's not waiting for condition in waitsFor and directly runs the last block. anyone seen similar issue or has any explanation? Whats the best way to use timeouts with istanbul then?

**Comment by maenu** [comment]
I remember having timing troubles with asynchronous testing with jasmine when running the tests on the instrumented sources on phantomjs. It seems to work much better with the [clock of jasmine 2](http://jasmine.github.io/edge/introduction.html#section-Jasmine_Clock).

**Comment by gyandeeps** [comment]
Please reopen if the issue persists.
