### ISSUE TITLE
Breaking: Latest release of `lodash` 3.0.0 breaks this utility

### ISSUE THREAD

**Issue by gyandeeps** [maenu/grunt-template-jasmine-istanbul#36]
The latest build of `lodash` 3.0.0 breaks the functionality of this utility.
It gives the following error and freezes:

```.sh
Warning: PhantomJS timed out, possibly due to an unfinished async spec. Used --force, continuing.
```

**Comment by larsthorup** [comment]
Works. Thx!

**Comment by maenu** [comment]
You are right, we need to be more restrictive on dependencies so this package isn't rendered unusable by new versions of them.

**Comment by jdalton** [comment]
\o/
