### ISSUE TITLE
templateOptions.replace to `false` hangs up phantomjs

### ISSUE THREAD

**Issue by gyandeeps** [maenu/grunt-template-jasmine-istanbul#40]
when I use the option `templateOptions.replace = false` then the `Phantomjs` hangs up.

**Comment by maenu** [comment]
That seems to be caused by a `ReferenceError` because of a bad undefined check in the reporter. Would be solved by merging #30.

**Comment by alexpelan** [comment]
+1 for (what looks like) this issue - I'm using the client complex require template, and my tests run and pass, but then phantom hangs and the coverage isn't generated.

**Comment by ritchieanesco** [comment]
+1 Has any1 come close to resolving this?

**Comment by gyandeeps** [comment]
closed via #30
