### ISSUE TITLE
Dependency version ranges are to lax

### ISSUE THREAD

**Issue by maenu** [maenu/grunt-template-jasmine-istanbul#41]
#36 has shown that the restrictions on dependency versions are too lax. As @larsthorup has pointed out `>=` is prone to breaking this package when a dependency introduces breaking changes. We need to use `1.2.x` or `~1.2.3` or `^1.2.3`.

**Comment by gyandeeps** [comment]
+1

**Comment by gyandeeps** [comment]
I am going to implement this in next few days.
