### ISSUE TITLE
Can't find variable: require

### ISSUE THREAD

**Issue by msieurtoph** [maenu/grunt-template-jasmine-istanbul#45]
I probably missed something, thx for your help...

I am trying to test and cover a simple js file (a future node module) and following the simple example, I get this error : 

```
$ grunt test
>> Local Npm module "grunt-template-jasmine-istanbul" not found. Is it installed?

Running "jasmine:coverage" (jasmine) task
Testing jasmine specs via PhantomJS

>> ReferenceError: Can't find variable: require at
>> xxxxxxxxxxxxxxxxxxx\.grunt\grunt-contrib-jasmine\xxxxxxxx.js:9
>> ReferenceError: Can't find variable: require at
>> xxxxxxxxxxxxxxxxxxx\spec\xxxxxxxx.spec.js:3
Warning: No specs executed, is there a configuration error? Use --force to continue.

Aborted due to warnings.
```

First of all, I do not understand why it tells me : `Local Npm module "grunt-template-jasmine-istanbul" not found`, because this module is properly installed locally : 

```
$ npm list --depth=0                                                                       
xxxxxxxx@0.2.0       
├── grunt@0.4.5                                                                            
├── grunt-contrib-jasmine@0.8.2                                                            
├── grunt-contrib-jshint@0.11.2                                                            
├── grunt-contrib-watch@0.6.1                                                              
├── grunt-newer@1.1.0                                                                      
├── grunt-template-jasmine-istanbul@0.3.3                                                  
├── jshint-stylish@2.0.0                                                                   
├── load-grunt-tasks@3.2.0                                                                 
├── lodash@3.9.3                                                                           
├── slash@1.0.0                                                                            
└── time-grunt@1.2.1                

$ npm list -g --depth=0
xxxxxxxxxxxxxxxxxxx\npm
├── generator-angular@0.11.0
├── generator-karma@1.0.0
├── grunt-cli@0.1.13
├── npm_lazy@1.7.0
├── release-it@0.0.15
└── yo@1.4.5                                                       
```

And I do not understand why I get the ReferenceError about the `require` method neither. `require` is supposed to be a native node method, no ?

What did I do wrong ?

**Comment by gyandeeps** [comment]
Answer to the second question: `require` is not native to browser that why you are getting the error there. Remember these test are run in browser context.
In your folder structure do you actually have `grunt-template-jasmine-istanbul` installed?
Can you share the part of gruntfile where you make the jasmine call?

**Comment by maenu** [comment]
As I remember, there has once been an issue with `load-grunt-tasks`, see https://github.com/maenu/grunt-template-jasmine-istanbul/issues/8#issuecomment-30163512.
It can be resolved with the reference configuration, but I have no idea what's causing it.

**Comment by msieurtoph** [comment]
@maenu : Thx, it fixed the `module not found` issue. 
I guess we need to exclude the 'grunt-template-jasmine-istanbul' task from the global tasks load, because it will be loaded later, during execution (https://github.com/sindresorhus/load-grunt-tasks/issues/5)

@gyandeeps : Thx, I did not notice this 'huge' point about browser context. 
As far as I am developping a plugin for a grunt module, it does not make sense to test it in browser context. 
So is this module still the proper tool to test my project? My google searches all drove me to it. 

If it is, can you tell me how to make the browser context know about the `require` method ? (using browerify does not seem to work) 
If not, do you have suggestion to locally run jasmine tests and get coverage reports, before pushing to github for example?

**Comment by gyandeeps** [comment]
You should use https://github.com/mhevery/jasmine-node for jasmine node integration.
I personally  use mocha for node modules.
