### ISSUE TITLE
There is a question about Istanbul, hope to get help

### ISSUE THREAD

**Issue by silentzone** [maenu/grunt-template-jasmine-istanbul#53]
the tool is very nice! but coverage inaccuracy.
Anonymous function and closure not covered like this :  
```
 (function() {  ....[ can‘t coverage code ] ... })();
or
define(function() { 
   ....[ can‘t coverage code ] ... 
})();
```
![image](https://cloud.githubusercontent.com/assets/273957/10836501/3210c95e-7ee9-11e5-886a-aaf30c0a99bf.png)

**Comment by gyandeeps** [comment]
I think this would be a appropriate question for the Istanbul project as this module doesnt decide how code coverage is calculated.

**Comment by silentzone** [comment]
OK, thanks
